#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Menu Id
#define IDM_MAIN 100
#define IDM_LISTVIEW 101

// Dialogs
#define IDD_MAIN 100
#define IDD_ENTRIES 101

// Main Dlg
#define IDC_REBAR 102
#define IDC_TOOLBAR 103
#define IDC_SEARCH 104
#define IDC_TAB 105
#define IDC_ALL 106
#define IDC_LOGON 107
#define IDC_PENDINGFILERENAME 108
#define IDC_KNOWNDLLS 109
#define IDC_IMAGEHIJACKS 110
#define IDC_CODECS 111
#define IDC_WEB 112
#define IDC_TASKSCHEDULER 113
#define IDC_SERVICES 114
#define IDC_DRIVERS 115
#define IDC_STATUSBAR 116

// Settings Dlg
#define IDC_NAV 117
#define IDC_RESET 118
#define IDC_SAVE 119
#define IDC_CLOSE 120

#define IDC_IMAGEHIJACKS_CHK 121
#define IDC_WEB_CHK 122
#define IDC_PENDINGFILERENAME_CHK 123
#define IDC_CODECS_CHK 124
#define IDC_KNOWNDLLS_CHK 125
#define IDC_TASKSCHEDULER_CHK 126
#define IDC_SERVICES_CHK 127
#define IDC_DRIVERS_CHK 128

// Main Menu
#define IDM_RUNASADMIN 129
#define IDM_SETTINGS 130
#define IDM_SAVE_HTML 131
#define IDM_EXIT 132
#define IDM_FIND 133
#define IDM_ALWAYSONTOP_CHK 134
#define IDM_DARKMODE_CHK 135
#define IDM_SKIPUACWARNING_CHK 136
#define IDM_USECERTIFICATES_CHK 137
#define IDM_CHECKUPDATES_CHK 138
#define IDM_WEBSITE 139
#define IDM_CHECKUPDATES 140
#define IDM_DONATE 141
#define IDM_ABOUT 142

// Listview Menu
#define IDM_EXPLORE_FILE 143
#define IDM_EXPLORE_REGISTRY 144
#define IDM_COPY 145
#define IDM_COPY_VALUE 146
#define IDM_DELETE 147
#define IDM_REFRESH 148

#define IDM_SELECT_ALL 149
#define IDM_ZOOM 150
#define IDM_TAB_NEXT 151
#define IDM_TAB_PREV 152

#define IDX_LANGUAGE 1000

// Strings
#define IDS_UPDATE_NO 1
#define IDS_UPDATE_YES 2
#define IDS_UPDATE_DOWNLOAD 3
#define IDS_UPDATE_DONE 4
#define IDS_UPDATE_ERROR 5
#define IDS_UPDATE_INIT 6
#define IDS_UPDATE_INSTALL 7
#define IDS_UPDATE_SPEED 8
#define IDS_RESET 9
#define IDS_SAVE 10
#define IDS_CLOSE 11
#define IDS_FILE 12
#define IDS_VIEW 13
#define IDS_SETTINGS 14
#define IDS_HELP 15
#define IDS_RUNASADMIN 16
#define IDS_SAVE_HTML 17
#define IDS_EXIT 18
#define IDS_REFRESH 19
#define IDS_FIND 20
#define IDS_LANGUAGE 21
#define IDS_WEBSITE 22
#define IDS_CHECKUPDATES 23
#define IDS_DONATE 24
#define IDS_ABOUT 25
#define IDS_EXPLORE_FILE 26
#define IDS_EXPLORE_REGISTRY 27
#define IDS_DELETE 28
#define IDS_COPY 29
#define IDS_COPY_VALUE 30
#define IDS_ENTRIES 31
#define IDS_NAME 32
#define IDS_VALUE 33
#define IDS_ALL 34
#define IDS_LOGON 35
#define IDS_WEB 36
#define IDS_PENDINGFILERENAME 37
#define IDS_CODECS 38
#define IDS_KNOWNDLLS 39
#define IDS_TASKSCHEDULER 40
#define IDS_SERVICES 41
#define IDS_DRIVERS 42
#define IDS_IMAGEHIJACKS 43
#define IDS_FILEPATH 44
#define IDS_SIGNATURE 45
#define IDS_ALWAYSONTOP_CHK 46
#define IDS_DARKMODE_CHK 47
#define IDS_USECERTIFICATES_CHK 48
#define IDS_SKIPUACWARNING_CHK 49
#define IDS_CHECKUPDATES_CHK 50
#define IDS_QUESTION_ADMIN 51
#define IDS_QUESTION_DELETE 52
#define IDS_PROPERTIES 53
#define IDS_STATUS_TOTAL 54
#define IDS_STATUS_LOADING 55
#define IDS_STATUS_EMPTY 56
#define IDS_STATUS_FINISH 57

// PNG
#define IDP_SEARCH_LIGHT 100
#define IDP_SEARCH_DARK 101
#define IDP_DELETE 102
#define IDP_REFRESH 103
#define IDP_DONATE 104

// Icons
#define IDI_MAIN 100
#define IDI_EMPTY 101
#define IDI_WAIT 102
#define IDI_FULL 103

#endif // __RESOURCE_H__
